### ISSUE TITLE
ValueError: 9216 is not a valid InputAttack

### ISSUE THREAD

**Issue by massivemax** [Alchemy-Meister/TekkenBot#10]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tkinter\__init__.py", line 749, in callit
  File "tekken\launcher.py", line 67, in __update_launcher
  File "tekken_game_state.py", line 74, in update
  File "tekken\process_io_manager.py", line 90, in update
  File "tekken\game_reader.py", line 384, in get_updated_state
  File "tekken\game_reader.py", line 571, in initialize_bots
  File "tekken\bot_snapshot.py", line 73, in __init__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 310, in __call__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 564, in __new__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 548, in __new__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 577, in _missing_
ValueError: 9216 is not a valid InputAttack

**Comment by Alchemy-Meister** [comment]
Any context when this happened? Online mode? Characters being used?

**Comment by massivemax** [comment]
I'm playing Bryan against King, ranked online. I've gotten the same error (not the same numbers) against a handful of other characters, Lei being the only one I remember for certain.

**Comment by Alchemy-Meister** [comment]
I don't know the meaning of those new values yet, so I have implemented a quick solution that ignores those values and treats them as Null:
https://github.com/Alchemy-Meister/TekkenBot/releases/tag/0.1.19b2

More testing and feedback is need before I can release this build publicly

**Comment by Alchemy-Meister** [comment]
Closing as stated on #13
