### ISSUE TITLE
Punish Alarm Mode doesn't work

### ISSUE THREAD

**Issue by Nawjy** [Alchemy-Meister/TekkenBot#15]
This has been an issue for me for a while, but up until now I've just been living without it. When trying to switch the Overlay to Mode>Punish Alarm (loud!) Tekken Bot Prime outputs this:
`Closing punish window, result: NO_PUNISH
Exception in Tkinter callback

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "gui\view\tekken_bot_prime_view.py", line 457, in <lambda>
  File "gui\view\tekken_bot_prime_view.py", line 596, in __integrity_checker
  File "gui\view\tekken_bot_prime_view.py", line 735, in __update_overlay_themes_swap
  File "gui\controller\tekken_bot_prime_controller.py", line 142, in overlay_mode_change
  File "gui\my_tkinter\overlay\overlay_manager.py", line 204, in change_overlay_mode
  File "gui\my_tkinter\overlay\overlay_manager.py", line 345, in __add_overlay
  File "patterns\factory\factory.py", line 50, in create_class
ValueError: unknown class for id: 2`

Is this an issue anyone else has? I've been wondering if there is just a problem on my end or if the Punish Alarm ceased to be supported or something. Thanks.

**Comment by Alchemy-Meister** [comment]
The Punish Overlay it's just a placeholder, I haven't reimplemented yet. What I did, is add an overlay independent punish alarm that can be enabled as shown in the following image:
<img width="920" alt="Screen Shot 2019-12-16 at 10 11 38 PM" src="https://user-images.githubusercontent.com/5882817/70943417-20072380-2051-11ea-965a-7ba3a2e9879a.png">

**Comment by Nawjy** [comment]
Thank you for clarifying that, that's all I really needed to know.
